# BACKGROUND
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# INPUT FIELD (ô nhập password)
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(151515ff)
    inner_color = rgba(200, 200, 200, 0.1)
    font_color = rgba(255, 255, 255, 1)

    fade_on_empty = false
    rounding = 10

    position = 0, -80
    halign = center
    valign = center
}

# LABEL (giờ)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 80
    color = rgba(255, 255, 255, 0.8)

    position = 0, 150
    halign = center
    valign = center
}

# LABEL (ngày)
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    font_size = 20
    color = rgba(255, 255, 255, 0.6)

    position = 0, 80
    halign = center
    valign = center
}
